let laCarte = {
  fooding: [
    'Nachos',
    'Planche Mixte',
    'Planche Fromage',
    'Pizza Margarita',
    'Pizza 4 Fromages',
    'Pizza Reine',
  ],
  vins: [
    'Roseline',
    'Macon Milly',
    'Grand Ardèche',
    'Saint Veran',
    'Hautes Côtes de Beaune Blanc',
    "P'tit Chablis",
    'Irancy',
    'Marranges',
    'Givry',
    'Hautes Côtes de Beaune Blanc',
    'Crémant',
  ],
  cocktails: [
    "Bal'tazar",
    'Coeur Mandarine',
    'Potion du Druide',
    'Smoke King Gin',
    'London Mule Pomelo',
    'Melkior',
    'Mojito',
    'Mojito Fraise',
    'Mojito Frambpoise',
    'Mojito Passion',
    'Ocean Tiki',
    'Tiki des îles',
    'Daïquiri Passion',
    'Pina Colada',
    'Planteur',
    'Cuban Mule Mandarine',
    'Love on the Beat',
    'Christmas Cosmo',
    'Moscow Mule',
    'Matcha Cha Cha',
    "Gaz'Part",
    'Tequila Sunrise',
    'Oh! Kiwi!',
    'Margarita',
    'Mexican Mule',
    'Scotch Mule',
  ],
  spritz: [
    'Spritz',
    'Holyday Spritz',
    "Aphrodi'Spritz",
    'Spritz Bergamotte',
    'Sea Sex & Spritz',
    'London Basilic Spritz',
    '007 Agent Spritz',
    'French Spritz',
    'Saint Germain Spritz',
    'Spritz sans Alcool',
  ],
  dry: [
    'London Spirit',
    'Ginger Spirit',
    'Spritz Spirit',
    'Mojito Spirit',
    'Rhumba Spirit',
    'Spïki Spirit',
  ],
  alcools: [
    [
      'Vodka',
      'Vodka RB',
      'Vodka pomme',
      'Vodka orange',
      'Vodka ananas',
      'Vodka perrier',
      'Vodka tonic',
    ],
    [
      'Absolut',
      'Absolut RB',
      'Absolut pomme',
      'Absolut orange',
      'Absolut ananas',
      'Absolut perrier',
      'Absolut tonic',
    ],

    ['Captain', 'Captain coca', 'Captain orange', 'Captain ananas'],
    ['Havana', 'Havana coca', 'Havana orange', 'Havana ananas'],
    [
      'Havana 7 ans',
      'Havana 7 ans  coca',
      'Havana 7 ans orange',
      'Havana 7 ans ananas',
      'Havana 7ans Perrier',
    ],
    [
      '3 rivières',
      '3 rivières coca',
      '3 rivières orange',
      '3 rivières ananas',
    ],
    ['Zacapa', 'Zacapa coca', 'Zacapa orange', 'Zacapa ananas'],
    ['Diplomatico', 'Diplomatico Coca', 'Diplomatico Glace'],
    ['Gin', 'Gin tonic', 'Gin perrier'],
    ['Tanqueray Ten', 'Tanqueray Ten Tonic'],
    ['Henricks', 'Hendricks Tonic', 'Hendricks Perrier'],
    ["Gin de l'Herbier"],

    [
      'Briottet vert',
      'Briottet vert glaçons',
      'Briottet Vert Perrier',
    ],
    ['JB', 'JB coca', 'JB orange', 'JB ananas'],
    ['Jameson', 'Jameson Coca', 'Jameson Orange'],
    ['Jack', 'Jack coca'],
    ['Jack Honey', 'Jack Honey Coca'],
    [
      "Ballantine's",
      "Balantine's Coca",
      "Ballantine's Orange",
      "Ballantine's Perrier",
    ],
    ['Jager', 'Jager RB', 'Jager coca', 'Jager orange'],
    ['Tequila', 'Tequila Orange', 'Tequila Ananas', 'Tequila Coca'],
    ["Bailey's", "Bailey's glaçons"],
    ['Martini', 'Martini Blanc', 'Martini rouge'],
    ['Kir', 'Kir mûre', 'Kir framboise', 'Kir royal'],
    ['Lillet tonic', 'Lillet Agrum'],
    ['Ice tropez'],

    [
      'Briottet blanc',
      'Briottet blanc glaçons',
      'Briottet blanc perrier',
    ],
    ['Ricard', 'Perroquet', 'Tomate', 'Mauresque'],
    ['Malibu', 'Malibu orange', 'Malibu ananas', 'Malibu coca'],
  ],
  bieres: [
    'Licornes',
    'El Grande',
    'Slash Red',
    'Brooklyn',
    'Carte 10€',
    'Carte 15€',
    'Carte 20€',
    'Carte 25€',
    'Carte 50€',
  ],
  softs: [
    'Vittel',
    'Perrier',
    'Pomme',
    'Orange',
    'Ananas',
    'Abricot',
    'Raisin',
    'Tomate',
    'Pepsi',
    'Pepsi Max',
    'S.Agrum',
    'S.Tonic',
    'Ice Tea',
    'Orangina',
    '7up',
    'Red Bull',
    'Red Bull Pastèque',
  ],
  mocktails: [
    'Virgin Mojito',
    'Virgin Mojito Fraise',
    'Virgin Mojito Framboise',
    'Virgin Mojito Passion',
    'Virgin Love',
    'Potion du Dragon',
    'Kiwi qui Rit',
    'Virgin Mule Mangue',
    'Virgin Pina Colada',
  ],
  champagne: [
    'Coupe Mercier',
    'Coupe Moët',
    'Piscine Mercier',
    'Piscine Moët',
  ],
  BouteillesVins: [
    'Bouteille Roseline',
    'Bouteille Macon-Milly',
    'Bouteille Grand Ardèche',
    'Bouteille Saint Veran',
    'Bouteille HCB Blanc',
    'Bouteille Ptit Chablis',
    'Bouteille Irancy',
    'Bouteille Maranges',
    'Bouteille Givry',
    'Bouteille HCB Rouge',
    'Bouteille Crémant',
  ],
  BouteillesChamp: [
    'Bouteille Mercier',
    'Bouteille Moët',
    'Bouteille Mumm',
    'Bouteille Veuve',
    'Bouteille Vranken',
    'Bouteille Moët Rosé',
    'Bouteille Dom Perignon',
    'Bouteille Armand de Brignac',
    'Magnum Moët',
    'Magnum Veuve',
    'Magnum Dom Pérignon',
  ],
  BouteilleAlcool: [
    'Bouteille Absolut',
    'Bouteille Absolut Elyx',
    'Bouteille Belvédère',
    'Magnum Belvédère',
    "Bouteille Ballantine's",
    'Bouteille Jameson',
    'Bouteille Lagavulin',
    'Bouteille Jack',
    'Bouteille Jack Honey',
    'Bouteille Jack Pomme',
    'Bouteille Tanqueray',
    'Bouteille Tanqueray Ten',
    'Bouteille Herbier',
    'Bouteille Captain',
    'Bouteille Havana 3 ans',
    'Bouteille Havana 7 ans',
    'Bouteille Zacapa',
    'Bouteille Diplomatico',
    'Bouteille Briottet Vert',
    'Bouteille Briottet Blanc',
    'Bouteille Malibu',
    'Bouteille Jager',
    'Bouteille Tequila',
    'Pack RedBull Btlle',
  ],
};

export default laCarte;
